export const reducerCases = {
    SET_TOKEN : 'SET_TOKEN',
    SET_PLAYLISTS:'SET_PLAYLISTS',
    SET_USER:'SET_USER',
    SET_ARTIST:'SET_ARTIST',
    SET_ALBUMS:'SET_ALBUMS',
    SET_PLAYLIST:'SET_PLAYLIST'
}